linters-settings:
  dupl:
    threshold: 60
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  govet:
    check-shadowing: true
linters:
  disable-all: true
  enable:
    - gosec
    - gosimple
    - govet
    - gocritic
    - goconst
    - exportloopref
    - makezero
    - musttag
    - noctx
    - prealloc
    - reassign
    - sqlclosecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - containedctx
    - contextcheck
    - dogsled
    - dupl
run:
  skip-files:
    - ".*._test.go"
  timeout: 5m
  concurrency: 1